name: "🐞 Bug report"
description: "Create a report to help us reproduce and fix the bug"


body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting this issue to help us improve!
        If you have already identified the reason, we strongly appreciate you creating a new PR to fix it [here](https://github.com/open-mmlab/mmdetection/pulls)!
        If this issue is about installing MMCV, please file an issue at [MMCV](https://github.com/open-mmlab/mmcv/issues/new/choose).
        If you need our help, please fill in as much of the following form as you're able.

  - type: checkboxes
    attributes:
      label: Prerequisite
      description: Please check the following items before creating a new issue.
      options:
      - label: I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
        required: true
      - label: I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
        required: true
      - label: The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).
        required: true

  - type: textarea
    attributes:
      label: 🐞 Describe the bug
      description: |
        Please provide a clear and concise description of what the bug is.
        Preferably a simple and minimal code snippet that we can reproduce the error by running the code.
      placeholder: |
        A clear and concise description of what the bug is.

        ```python
        # Sample code to reproduce the problem
        ```

        ```shell
        The command or script you run.
        ```

        ```
        The error message or logs you got, with the full traceback.
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        Please run `python mmedit/utils/collect_env.py` to collect necessary environment information and paste it here.
        You may add addition that may be helpful for locating the problem, such as
          - How you installed PyTorch \[e.g., pip, conda, source\]
          - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Tell us anything else you think we should know.
      placeholder: |
        1. Did you make any modifications on the code or config? Did you understand what you have modified?
        2. What dataset did you use?
        3. What do you think might be the reason?
