name: 🚀 Feature request
description: Suggest an idea for this project
labels: [feature request]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea to make MMDetection better.
        We strongly appreciate you creating a PR to implete this feature [here](https://github.com/open-mmlab/mmdetection/pulls)!

        If you need our help, please fill in as much of the following form as you're able.

  - type: textarea
    attributes:
      label: What is the problem this feature will solve?
      placeholder: |
        E.g., It is inconvenient when \[....\].
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is the feature you are proposing to solve the problem?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What alternatives have you considered?
      description: |
        Add any other context or screenshots about the feature request here.
